### ISSUE TITLE
Groupings for Structured Diff Pruning

### ISSUE THREAD

**Issue by varunnair18** [dguo98/DiffPruning#3]
In section 4.3 of the paper, it states:

"Grouping for the structured version of diff pruning is based on the matrix/bias vectors (i.e. parameters that belong to the same matrix or bias vector are assumed to be in the same group), which results in 393 groups."

How is that value of 393 computed, and where can we find the code that relates to the creation of those groupings?

I think the per_layer_alpha flag in `run_glue_diffpruning.py` is used to set the groupings on a per layer basis, but I can't see a `per_layer_z` and `per_layer_z_grad` variable (since there is a `per_param_z` and `per_param_z_grad.`)

**Comment by dguo98** [comment]
Hi Varun,

The grouping is simply based on parameters with the same name. 

per_layer_z, per_param_z are deprecated - so don't worry about them!

I've explained more details in my response to your email thread. Let me know if you have additional questions.

**Comment by varunnair18** [comment]
Thanks for your note - will get back to you over email!

**Comment by shi-kejian** [comment]
Hi. Again, thank you for the amazing work.
I have a quick follow-up
"per_layer_z, per_param_z are deprecated - so don't worry about them!" 
-- So in the codebase it's default structured diff-pruning right? We don't really set these two configs. 

Thank you.
