### ISSUE TITLE
gradient update

### ISSUE THREAD

**Issue by Ericmututu** [dguo98/DiffPruning#4]
Hi,
It is a wonderful work. When I tried to understand the source code, I ran into a very confusing problem. The two line codes in [line435](https://github.com/dguo98/DiffPruning/blob/085fa7d9e2bcbcd19f705a08b1c0c6c74c54bada/examples/run_glue_diffpruning.py#L435) and [line439](https://github.com/dguo98/DiffPruning/blob/085fa7d9e2bcbcd19f705a08b1c0c6c74c54bada/examples/run_glue_diffpruning.py#L439) that confuse me. This looks like some kind of chain rule. Is there a clearer explanation?

Thanks in advance.

**Comment by Ericmututu** [comment]
I understand.

**Comment by shi-kejian** [comment]
@Ericmututu I struggle at this too -- could you kindly explain here if you've figured it out? Thank you.
